# syntax=docker/dockerfile:1.7
ARG SOURCE_DIR=sources/postgrest
ARG NIX_ATTR=postgrestStatic
ARG NIX_EXPRESSION=static-v14_10-arm64.nix

FROM nixos/nix:2.24.11 AS builder
ARG SOURCE_DIR
ARG NIX_ATTR
ARG NIX_EXPRESSION
WORKDIR /src
COPY ${SOURCE_DIR}/ ./
COPY services/postgrest/nix/ /overlay/
RUN mkdir -p /etc/nix \
  && printf '%s\n' \
    'always-allow-substitutes = true' \
    'max-jobs = auto' \
    'extra-substituters = https://postgrest.cachix.org' \
    'extra-trusted-public-keys = postgrest.cachix.org-1:icgW4R15fz1+LqvhPjt4EnX/r19AaqxiVV+1olwlZtI=' \
    >> /etc/nix/nix.conf
RUN rm -f .git \
  && nix-build "/overlay/${NIX_EXPRESSION}" -A ${NIX_ATTR} --arg sourceDir /src \
  && mkdir -p /rootfs/bin \
  && cp result/bin/postgrest /rootfs/bin/postgrest \
  && chmod 0755 /rootfs/bin/postgrest

FROM scratch AS artifact
COPY --from=builder /rootfs/ /
