ARG BASE_IMAGE=gcr.io/distroless/cc-debian13
FROM ${BASE_IMAGE}
ARG ARTIFACT_ROOT
WORKDIR /app
COPY ${ARTIFACT_ROOT}/ /
EXPOSE 4000
ENTRYPOINT ["/usr/bin/tini", "-s", "-g", "--", "/usr/bin/sh", "/app/run.sh"]
CMD ["/usr/bin/sh", "/app/bin/server"]
